### ISSUE TITLE
从第 8 个 epoch 开始，val loss 就一直在上升

### ISSUE THREAD

**Issue by Wonderdch** [yieshah/PLSPL#2]
你好，我在使用你提供的 NYC 数据时，发现第 8 个 epoch 时性能就达到了巅峰，后面的 epoch 中 val loss 就一直在上升。

我想知道你在实验时也是这样吗？还是因为你提供的默认参数很好，所以才早早得达到 val 性能巅峰？

PS：感谢你将这份代码开源，它很简洁的，看着很舒服 👍

**Comment by yieshah** [comment]
你好，非常感谢你的关注，我当时跑的时候也有这种情况的

**Comment by yieshah** [comment]
> 你好，我在使用你提供的 NYC 数据时，发现第 8 个 epoch 时性能就达到了巅峰，后面的 epoch 中 val loss 就一直在上升。
> 
> 我想知道你在实验时也是这样吗？还是因为你提供的默认参数很好，所以才早早得达到 val 性能巅峰？
> 
> PS：感谢你将这份代码开源，它很简洁的，看着很舒服 👍

**Comment by YuxiaWu** [comment]
@Wonderdch 你好，非常感谢你的关注，我当时跑的时候也有这种情况的
